#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
#########################################################
# Name: launcher.py
# Porpose: main launch script of videomass2
# Compatibility: Python2
# Author: Gianluca Pernigoto <jeanlucperni@gmail.com>
# Copyright: (c) 2018/2019 Gianluca Pernigoto <jeanlucperni@gmail.com>
# license: GPL3
# Rev (10) December 29 2018
#########################################################

# This file is part of Videomass2.

#    Videomass2 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    Videomass2 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with Videomass2.  If not, see <http://www.gnu.org/licenses/>.

#########################################################

import sys
import platform

if __name__ == '__main__':
    if sys.version_info[0] > 2:
        sys.stderr.write(u"[ERROR] Not a supported Python version. Need 2.7+\n"
                     u"You are using Python version %s\n"
                     u"Instead, you could install or build a compatible "
                     u"version of Videomass3 with Python3.\n" % sys.version)
        sys.exit(1)
    try:
        import wx
        
    except ImportError:
        if 'bdist_wheel' not in sys.argv:
            sys.stderr.write("[ERROR] 'wx' module is required!\n"
                             "Videomass2 need wxPython-Classic\n")
            
            if ['Windows', 'Darwin'] in platform.system():
                sys.stderr.write(
                    u"Please, install wxPython-Classic, you could find it here:\n"
                    u"<https://sourceforge.net/projects/wxpython/files/wxPython/>\n"
                                )
            else:
                sys.stderr.write('Please, install wxPython with your package'
                                 'manager.\n')
            sys.exit(1)
    
    from videomass2 import Videomass2
    Videomass2.main()
