#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
#########################################################
# Name: launcher.py
# Porpose: main launch script of videomass2
# Compatibility: Python3, Python2
# Author: Gianluca Pernigoto <jeanlucperni@gmail.com>
# Copyright: (c) 2018/2019 Gianluca Pernigoto <jeanlucperni@gmail.com>
# license: GPL3
# Rev (10) December 29 2018
#########################################################

# This file is part of Videomass2.

#    Videomass2 is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    Videomass2 is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with Videomass2.  If not, see <http://www.gnu.org/licenses/>.

#########################################################
import sys

if __name__ == '__main__':
    
    if sys.version_info[0] == 2: # Python2 with wxPython Classic
        try:
            from videomass2 import Videomass2
            #import wx
        except ImportError as err:
                sys.stderr.write("ERROR: wxPython Classic is required (%s).\n" 
                                 % err)
                sys.exit(1)
        
    elif sys.version_info[0] == 3: # Python3 with wxPython Phoenix
        try:
            from videomass3 import Videomass2
            #import wx
        except ImportError as err:
                sys.stderr.write("ERROR: wxPython Phoenix is required (%s).\n" 
                                 % err)
                sys.exit(1)
                        
    Videomass2.Main()



