.\" Created by jeanslack on June 6 2020
.\"
.TH VIDEOMASS "1" "5 June 2020" "Version 2.7.0" "videomass"

.SH NAME
videomass \- Cross-platform Graphical User Interface for FFmpeg and youtube-dl.

.SH SYNOPSIS
.B videomass

.SH DESCRIPTION
Videomass is not a converter - it provides a graphical interface for writing
presets and profiles for using FFmpeg without limits on formats and codecs with
high flexibility and a wide cataloging expandability in order to make all around
the conversion experiences.
Since version 2.0.0 released in December 10, 2019, it also provides a basic
graphical interface for youtube-dl video downloader.
Videomass is written in Python3 with the wxPython4 toolkit and can be started
on all main platforms.

.SH OPTIONS
The videomass executable does not take any options.

.SH MAINTAINER
jeanslack
.TP
- Gianluca Pernigotto -- Project leader and main developer

.SH HOMEPAGE
.I https://github.com/jeanslack/Videomass

.SH REPORTING BUGS
For bug reports, please send an e-mail to:
.TP
Gianluca Pernigotto <jeanlucperni@gmail.com>

.SH "AUTHOR"
This manual page was written by jeanslack <jeanlucperni@gmail.com>, for the
Debian project (but may be used by others).

.SH "SEE ALSO"
\&\fBffmpeg\fR\|(1), \&\fByoutube-dl\fR\|(1), \&\fBmpv\fR\|(1)

.SH COPYRIGHT
Copyright  ©  2015-2020  Free Software Foundation, Inc.  License GPLv3+: GNU
GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free  to  change  and  redistribute  it.
There is NO WARRANTY, to the extent permitted by law.
